[project]
name = "machinelearning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "keras>=3.6.0",
    "numpy==1.26.0",
    "tensorflow==2.18.0",
]
